[package]
name = "pw2repac-save-editor"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.33.2", features = ["default"] }
egui_extras = { version = "*", features = ["all_loaders"] }